name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read

    env:
      SIGNAL_CLI_VERSION: 'v0.14.3'
      LIB_SIGNAL_VERSION: '0.92.2'

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            auth.docker.io:443
            download.oracle.com:443
            ghcr.io:443
            github.com:443
            ports.ubuntu.com:80
            production.cloudflare.docker.com:443
            registry-1.docker.io:443

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@60c26726de13f8b90771df4bc1641a52a3159994 # v1.5.2
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout signal-cli
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: 'AsamK/signal-cli'
          ref: ${{ env.SIGNAL_CLI_VERSION }}
          fetch-depth: 1

      - name: Cache patched libsignal-client library
        id: cache-native-lib
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: /opt/libsignal
          key: ${{ runner.os }}-build-${{ env.SIGNAL_CLI_VERSION }}-${{ env.LIB_SIGNAL_VERSION }}

      - name: Download libsignal and native library
        if: ${{ steps.cache-native-lib.outputs.cache-hit != 'true' }}
        run: |
          mkdir /opt/libsignal
          cd /tmp
          curl -Lo libsignal-client.jar  https://build-artifacts.signal.org/libraries/maven/org/signal/libsignal-client/${{ env.LIB_SIGNAL_VERSION }}/libsignal-client-${{ env.LIB_SIGNAL_VERSION }}.jar
          curl -Lo native.tgz https://github.com/exquo/signal-libs-build/releases/download/libsignal_v${{ env.LIB_SIGNAL_VERSION }}/libsignal_jni.so-v${{ env.LIB_SIGNAL_VERSION }}-aarch64-unknown-linux-gnu.tar.gz
          tar -xf native.tgz
          zip libsignal-client.jar -d '*signal_jni*'
          zip libsignal-client.jar -uj libsignal_jni.so
          cp libsignal-client.jar /opt/libsignal/libsignal-client.jar

      - name: Build artifact
        run: ./gradlew --no-daemon -Plibsignal_client_path=/opt/libsignal/libsignal-client.jar nativeCompile

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: build/native/nativeCompile/signal-cli

